-- Email dummy buat akun demo (buyer_id di-set via variabel di command).
-- received_at makin baru ke atas.
INSERT INTO messages (id,buyer_id,to_addr,from_addr,subject,preview,html,text,received_at,seen,is_hub) VALUES
('demo-msg-1','__BID__','alice@demomail.co','Netflix <info@account.netflix.com>','Selesaikan pendaftaran Anda','Halo, tinggal satu langkah lagi untuk mulai menonton...','<div style="font-family:sans-serif;padding:16px"><h2 style="color:#e50914">NETFLIX</h2><p>Halo,</p><p>Tinggal <b>satu langkah lagi</b> untuk mulai menonton. Klik tombol di bawah untuk verifikasi email kamu.</p><p><a href="#" style="background:#e50914;color:#fff;padding:10px 18px;border-radius:4px;text-decoration:none">Verifikasi Email</a></p><p>Kode: <b>8842</b></p></div>','Halo, tinggal satu langkah lagi untuk mulai menonton. Kode: 8842',(strftime('%s','now')-180)*1000,0,0),
('demo-msg-2','__BID__','alice@demomail.co','Google <no-reply@accounts.google.com>','Kode verifikasi keamanan','Kode verifikasi Google Anda adalah 493021. Jangan bagikan ke siapa pun.','<div style="font-family:Roboto,sans-serif;padding:20px"><h3>Verifikasi 2 Langkah</h3><p>Kode verifikasi kamu:</p><p style="font-size:28px;font-weight:bold;letter-spacing:4px">493021</p><p style="color:#666">Berlaku 10 menit. Jangan bagikan kode ini.</p></div>','Kode verifikasi Google: 493021. Berlaku 10 menit.',(strftime('%s','now')-900)*1000,0,0),
('demo-msg-3','__BID__','bob@demomail.co','Discord <noreply@discord.com>','Verify your email address','Thanks for registering! Please verify your email to continue.','<div style="font-family:sans-serif;padding:16px;background:#5865F2;color:#fff;border-radius:8px"><h2>Discord</h2><p>Thanks for registering an account! Verify your email to get started.</p><p><a href="#" style="background:#fff;color:#5865F2;padding:10px 18px;border-radius:4px;text-decoration:none;font-weight:bold">Verify Email</a></p></div>','Thanks for registering! Verify your email to continue.',(strftime('%s','now')-2400)*1000,1,0),
('demo-msg-4','__BID__','alice@demomail.co','Amazon <shipment@amazon.com>','Pesanan kamu telah dikirim','Paket dengan nomor 703-88213 sedang dalam perjalanan.','<div style="font-family:Arial,sans-serif;padding:16px"><h2 style="color:#232f3e">amazon</h2><p>Pesanan kamu <b>#703-88213</b> telah dikirim dan diperkirakan tiba <b>besok</b>.</p><p><a href="#" style="background:#ff9900;color:#111;padding:8px 16px;border-radius:4px;text-decoration:none">Lacak Paket</a></p></div>','Pesanan #703-88213 telah dikirim, tiba besok.',(strftime('%s','now')-5400)*1000,1,0),
('demo-msg-5','__BID__','carol@tmpbox.io','GitHub <noreply@github.com>','[GitHub] Please verify your device','A new sign-in from Chrome on Windows. Verify it was you.','<div style="font-family:monospace;padding:16px"><h3>Device verification</h3><p>We noticed a new sign-in to your GitHub account from <b>Chrome on Windows</b>.</p><p>Verification code: <b>77-1290</b></p></div>','New sign-in from Chrome on Windows. Code: 77-1290',(strftime('%s','now')-9000)*1000,1,0),
('demo-msg-6','__BID__','alice@demomail.co','Spotify <no-reply@spotify.com>','Selamat datang di Spotify Premium','Akun Premium kamu sudah aktif. Nikmati musik tanpa iklan!','<div style="font-family:sans-serif;padding:16px;background:#191414;color:#fff;border-radius:8px"><h2 style="color:#1DB954">Spotify</h2><p>Selamat datang di <b>Premium</b>! Nikmati musik tanpa iklan, kualitas tinggi, dan download offline.</p></div>','Akun Spotify Premium kamu sudah aktif.',(strftime('%s','now')-14400)*1000,1,0),
('demo-msg-7','__BID__','carol@tmpbox.io','PayPal <service@paypal.com>','Konfirmasi pembayaran Rp150.000','Kamu telah mengirim Rp150.000 ke Toko Online Jaya.','<div style="font-family:sans-serif;padding:16px"><h2 style="color:#003087">PayPal</h2><p>Kamu telah mengirim <b>Rp150.000</b> ke <b>Toko Online Jaya</b>.</p><p>ID Transaksi: 9KJ22P</p></div>','Kamu mengirim Rp150.000 ke Toko Online Jaya. ID: 9KJ22P',(strftime('%s','now')-28800)*1000,1,0),
('demo-msg-8','__BID__','bob@demomail.co','LinkedIn <messages-noreply@linkedin.com>','Kamu punya 3 pesan baru','Rina dan 2 orang lainnya mengirimimu pesan.','<div style="font-family:sans-serif;padding:16px"><h2 style="color:#0a66c2">LinkedIn</h2><p><b>Rina</b> dan 2 orang lainnya mengirimimu pesan. Lihat sekarang.</p></div>','Rina dan 2 orang lainnya mengirimimu pesan.',(strftime('%s','now')-50000)*1000,1,0),
('demo-msg-9','__BID__','alice@demomail.co','OpenAI <noreply@openai.com>','Your login code','Your ChatGPT login code is 620-104.','<div style="font-family:sans-serif;padding:16px"><h3>Sign in to ChatGPT</h3><p>Your login code:</p><p style="font-size:24px;font-weight:bold">620-104</p></div>','Your ChatGPT login code is 620-104.',(strftime('%s','now')-90000)*1000,1,0),
('demo-msg-10','__BID__','carol@tmpbox.io','Instagram <security@mail.instagram.com>','Aktivitas login tidak dikenal','Kami mendeteksi login dari perangkat baru.','<div style="font-family:sans-serif;padding:16px"><h2>Instagram</h2><p>Kami mendeteksi login dari <b>perangkat baru</b> di Jakarta. Kalau ini kamu, abaikan email ini.</p></div>','Login dari perangkat baru di Jakarta terdeteksi.',(strftime('%s','now')-172800)*1000,1,0);
